# IMPORTAÇÃO DE BIBLIOTECAS E DRIVE

As 4 primeiras linhas foram adicionadas antes de saber o que seria necessário durante a execução do TCC. As seguintes foram acrescentadas assim que necessário.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.linear_model import ElasticNetCV

Montagem do Google Drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# IMPORTAÇÃO DE DADOS

11 Datasets de Doenças/Agravos à Saúde e 8 Datasets de Indicadores de Desenvolvimento diretamente relacionados à saúde e outros possivelmente relacionados à qualidade da saúde

In [3]:
aids_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oaids.csv")
animais_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oanimais.csv")
dengue_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/odengue.csv")
hanseniase_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/ohanseniase.csv")
hepatites_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/ohepatites.csv")
sifilis_adquirida_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/osadquirida.csv")
sifilis_congenita_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oscongenita.csv")
sifilis_gestante_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/osgestante.csv")
toxico_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/otoxico.csv")
tuberculose_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/otuberculose.csv")
violencia_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oviolencia.csv")
coordenadas_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/coordenadas.csv")
estabelecimentos_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/estabelecimentos.csv")
mortalidade_geral_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/mortalidadegeral.csv")
mortalidade_infantil_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/mortalidadeinfantil.csv")
nascimentos_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/nascimentos.csv")
pib_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/pib.csv")
populacao_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/populacao.csv")
profissionais_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/profissionais.csv")

#
 PROCESSAMENTO INICIAL DOS DATAFRAMES

Definição de índice em comum, exclusão de colunas duplicadas, renomeação de colunas evitando duplicidade

# AIDS

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Separação da coluna "cidade" em "codigo" (código saúde) e "cidade" (nome do município).

4) Definição do index como "codigo".

5) Reavaliação do dataframe após as mudanças realizadas.

In [4]:
aids_df.head()

                           cidade  aids
0    110001 Alta Floresta D'Oeste     1
1  110037 Alto Alegre dos Parecis     1
2             110040 Alto Paraíso     5
3         110034 Alvorada D'Oeste     5
4                110002 Ariquemes   121

In [5]:
aids_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oaids.csv")
aids_df[["codigo", "cidade"]] = aids_df["cidade"].str.split(n=1, expand=True)
aids_df = aids_df.set_index("codigo")
aids_df.head()

                         cidade  aids
codigo
110001    Alta Floresta D'Oeste     1
110037  Alto Alegre dos Parecis     1
110040             Alto Paraíso     5
110034         Alvorada D'Oeste     5
110002                Ariquemes   121

# DOENÇAS E AGRAVOS NOTIFICÁVEIS

1) Avaliação dos demais dataframes relacionados, comparação com o de AIDS e verificado que seguem o mesmo padrão.

2) Repetição de todas as etapas relatadas acima.

In [6]:
animais_df.head()

                           cidade  animais
0    110001 Alta Floresta D'Oeste      192
1  110037 Alto Alegre dos Parecis      199
2             110040 Alto Paraíso       62
3         110034 Alvorada D'Oeste       78
4                110002 Ariquemes      252

In [7]:
dengue_df.head()

                           cidade  dengue
0    110001 Alta Floresta D'Oeste     833
1  110037 Alto Alegre dos Parecis      90
2             110040 Alto Paraíso      65
3         110034 Alvorada D'Oeste     126
4                110002 Ariquemes     198

In [8]:
hanseniase_df.head()

                           cidade  hanseniase
0    110001 Alta Floresta D'Oeste          51
1  110037 Alto Alegre dos Parecis          86
2             110040 Alto Paraíso          43
3         110034 Alvorada D'Oeste          24
4                110002 Ariquemes         224

In [9]:
hepatites_df.head()

                           cidade  hepatites
0    110001 Alta Floresta D'Oeste         41
1  110037 Alto Alegre dos Parecis         12
2             110040 Alto Paraíso         66
3         110034 Alvorada D'Oeste          8
4                110002 Ariquemes        240

In [10]:
sifilis_adquirida_df.head()

                           cidade  sadquirida
0    110001 Alta Floresta D'Oeste          28
1  110037 Alto Alegre dos Parecis          13
2             110040 Alto Paraíso          18
3         110034 Alvorada D'Oeste          16
4                110002 Ariquemes         296

In [11]:
sifilis_congenita_df.head()

                           cidade  scongenita
0    110001 Alta Floresta D'Oeste           2
1  110037 Alto Alegre dos Parecis           1
2             110040 Alto Paraíso           2
3         110034 Alvorada D'Oeste           1
4                110002 Ariquemes           8

In [12]:
sifilis_gestante_df.head()

                           cidade  sgestante
0    110001 Alta Floresta D'Oeste         12
1  110037 Alto Alegre dos Parecis          2
2             110040 Alto Paraíso         11
3         110034 Alvorada D'Oeste          7
4                110002 Ariquemes         89

In [13]:
toxico_df.head()

                           cidade  toxico
0    110001 Alta Floresta D'Oeste     186
1  110037 Alto Alegre dos Parecis      31
2             110040 Alto Paraíso      18
3         110034 Alvorada D'Oeste      35
4                110002 Ariquemes     321

In [14]:
tuberculose_df.head()

                           cidade  tuberculose
0    110001 Alta Floresta D'Oeste           26
1  110037 Alto Alegre dos Parecis            4
2             110040 Alto Paraíso           12
3         110034 Alvorada D'Oeste            9
4                110002 Ariquemes          177

In [15]:
violencia_df.head()

,cidade,autoprovocada_sim,autoprovocada_não,autoprovocada_ignorado,autoprovocada_branco,violencia
0,110001 Alta Floresta D'Oeste,24,79,9,5,117
1,110037 Alto Alegre dos Parecis,1,3,-,-,4
2,110040 Alto Paraíso,-,9,1,-,10
3,110034 Alvorada D'Oeste,26,24,1,-,51
4,110002 Ariquemes,146,250,36,12,444

In [16]:
aids_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oaids.csv")
animais_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oanimais.csv")
dengue_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/odengue.csv")
hanseniase_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/ohanseniase.csv")
hepatites_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/ohepatites.csv")
sifilis_adquirida_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/osadquirida.csv")
sifilis_congenita_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oscongenita.csv")
sifilis_gestante_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/osgestante.csv")
toxico_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/otoxico.csv")
tuberculose_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/otuberculose.csv")
violencia_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/oviolencia.csv")

aids_df[["codigo", "cidade"]] = aids_df["cidade"].str.split(n=1, expand=True)
animais_df[["codigo", "cidade"]] = animais_df["cidade"].str.split(n=1, expand=True)
dengue_df[["codigo", "cidade"]] = dengue_df["cidade"].str.split(n=1, expand=True)
hanseniase_df[["codigo", "cidade"]] = hanseniase_df["cidade"].str.split(n=1, expand=True)
hepatites_df[["codigo", "cidade"]] = hepatites_df["cidade"].str.split(n=1, expand=True)
sifilis_adquirida_df[["codigo", "cidade"]] = sifilis_adquirida_df["cidade"].str.split(n=1, expand=True)
sifilis_congenita_df[["codigo", "cidade"]] = sifilis_congenita_df["cidade"].str.split(n=1, expand=True)
sifilis_gestante_df[["codigo", "cidade"]] = sifilis_gestante_df["cidade"].str.split(n=1, expand=True)
toxico_df[["codigo", "cidade"]] = toxico_df["cidade"].str.split(n=1, expand=True)
tuberculose_df[["codigo", "cidade"]] = tuberculose_df["cidade"].str.split(n=1, expand=True)
violencia_df[["codigo", "cidade"]] = violencia_df["cidade"].str.split(n=1, expand=True)

aids_df = aids_df.drop("cidade", axis=1)
animais_df = animais_df.drop("cidade", axis=1)
dengue_df = dengue_df.drop("cidade", axis=1)
hanseniase_df = hanseniase_df.drop("cidade", axis=1)
hepatites_df = hepatites_df.drop("cidade", axis=1)
sifilis_adquirida_df = sifilis_adquirida_df.drop("cidade", axis=1)
sifilis_congenita_df = sifilis_congenita_df.drop("cidade", axis=1)
sifilis_gestante_df = sifilis_gestante_df.drop("cidade", axis=1)
toxico_df = toxico_df.drop("cidade", axis=1)
tuberculose_df = tuberculose_df.drop("cidade", axis=1)
violencia_df = violencia_df.drop("cidade", axis=1)

aids_df = aids_df.set_index("codigo")
animais_df = animais_df.set_index("codigo")
dengue_df = dengue_df.set_index("codigo")
hanseniase_df = hanseniase_df.set_index("codigo")
hepatites_df = hepatites_df.set_index("codigo")
sifilis_adquirida_df = sifilis_adquirida_df.set_index("codigo")
sifilis_congenita_df = sifilis_congenita_df.set_index("codigo")
sifilis_gestante_df = sifilis_gestante_df.set_index("codigo")
toxico_df = toxico_df.set_index("codigo")
tuberculose_df = tuberculose_df.set_index("codigo")
violencia_df = violencia_df.set_index("codigo")

In [17]:
aids_df.head()

        aids
codigo
110001     1
110037     1
110040     5
110034     5
110002   121

In [18]:
animais_df.head()

        animais
codigo
110001      192
110037      199
110040       62
110034       78
110002      252

In [19]:
dengue_df.head()

        dengue
codigo
110001     833
110037      90
110040      65
110034     126
110002     198

In [20]:
hanseniase_df.head()

        hanseniase
codigo
110001          51
110037          86
110040          43
110034          24
110002         224

In [21]:
hepatites_df.head()

        hepatites
codigo
110001         41
110037         12
110040         66
110034          8
110002        240

In [22]:
sifilis_adquirida_df.head()

        sadquirida
codigo
110001          28
110037          13
110040          18
110034          16
110002         296

In [23]:
sifilis_congenita_df.head()

        scongenita
codigo
110001           2
110037           1
110040           2
110034           1
110002           8

In [24]:
sifilis_gestante_df.head()

        sgestante
codigo
110001         12
110037          2
110040         11
110034          7
110002         89

In [25]:
toxico_df.head()

        toxico
codigo
110001     186
110037      31
110040      18
110034      35
110002     321

In [26]:
tuberculose_df.head()

        tuberculose
codigo
110001           26
110037            4
110040           12
110034            9
110002          177

In [27]:
violencia_df.head()

,autoprovocada_sim,autoprovocada_não,autoprovocada_ignorado,autoprovocada_branco,violencia
codigo,,,,,
110001,24,79,9,5,117
110037,1,3,-,-,4
110040,-,9,1,-,10
110034,26,24,1,-,51
110002,146,250,36,12,444

# ESTABELECIMENTOS DE SAÚDE

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Separação da coluna "cidade" em "codigo" (código saúde) e "cidade" (nome do município).

4) Eliminação da coluna "Município".

5) Eliminação da coluna "cidade" para evitar duplicidade de informação (salva em outro dataframe).

6) Renomeação da coluna "Total" para não confundir com outras possíveis colunas semelhantes.

7) Definição do index como "codigo".

8) Reavaliação do dataframe após as mudanças realizadas.

In [28]:
estabelecimentos_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/estabelecimentos.csv")
estabelecimentos_df.head()

,Município,ACADEMIA DA SAÚDE,CENTRAL DE REGUALAÇÃO,CENTRAL DE REGULAÇÃO MÉDICA DAS URGÊNCIAS,CENTRO DE APOIO A SAÚDE DA FAMÍLIA-CASF,CENTRO DE ATENÇÃO HEMOTERÁPICA E/OU HEMATOLÓGICA,CENTRO DE ATENÇÃO PSICOSSOCIAL-CAPS,CENTRO DE PARTO NORMAL,CENTRO DE SAUDE/UNIDADE BASICA DE SAUDE,CENTRAL DE REGULACAO DE SERVICOS DE SAUDE,...,UNIDADE DE ATENCAO EM REGIME RESIDENCIAL,UNIDADE DE SERVICO DE APOIO DE DIAGNOSE E TERAPIA,UNIDADE DE VIGILANCIA EM SAUDE,UNIDADE MISTA,UNIDADE MOVEL DE NIVEL PRE-HOSP-URGENCIA/EMERGENCI,UNIDADE MOVEL FLUVIAL,UNIDADE MOVEL TERRESTRE,TELESAÚDE,POLO PREV.DE DOENCAS E AGRAVOS E PROMOCAO DA SAUDE,Total
0,110001 Alta Floresta D'Oeste,1,-,-,-,1,1,-,4,-,...,-,4,1,-,-,-,-,-,-,35
1,110037 Alto Alegre dos Parecis,1,-,-,-,-,-,-,6,-,...,-,2,1,-,-,-,-,-,-,14
2,110040 Alto Paraíso,-,-,-,-,-,-,-,4,-,...,-,4,1,-,-,-,-,-,-,19
3,110034 Alvorada D'Oeste,-,-,-,-,-,-,-,6,-,...,-,-,1,1,-,-,-,-,-,22
4,110002 Ariquemes,-,1,1,2,1,1,-,13,-,...,-,11,4,-,6,-,-,-,-,124

In [29]:
estabelecimentos_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/estabelecimentos.csv")
estabelecimentos_df[["codigo", "cidade"]] = estabelecimentos_df["Município"].str.split(n=1, expand=True)
estabelecimentos_df = estabelecimentos_df.drop("Município", axis=1)
estabelecimentos_df = estabelecimentos_df.drop("cidade", axis=1)
estabelecimentos_df = estabelecimentos_df.rename(columns={"Total": "total_de_estabelecimentos"})
estabelecimentos_df = estabelecimentos_df.set_index("codigo")
estabelecimentos_df.head()

,ACADEMIA DA SAÚDE,CENTRAL DE REGUALAÇÃO,CENTRAL DE REGULAÇÃO MÉDICA DAS URGÊNCIAS,CENTRO DE APOIO A SAÚDE DA FAMÍLIA-CASF,CENTRO DE ATENÇÃO HEMOTERÁPICA E/OU HEMATOLÓGICA,CENTRO DE ATENÇÃO PSICOSSOCIAL-CAPS,CENTRO DE PARTO NORMAL,CENTRO DE SAUDE/UNIDADE BASICA DE SAUDE,CENTRAL DE REGULACAO DE SERVICOS DE SAUDE,CENTRAL DE NOTIF. CAPTAÇÃO E DISTR. ÓRGÃOS ESTADUA,...,UNIDADE DE ATENCAO EM REGIME RESIDENCIAL,UNIDADE DE SERVICO DE APOIO DE DIAGNOSE E TERAPIA,UNIDADE DE VIGILANCIA EM SAUDE,UNIDADE MISTA,UNIDADE MOVEL DE NIVEL PRE-HOSP-URGENCIA/EMERGENCI,UNIDADE MOVEL FLUVIAL,UNIDADE MOVEL TERRESTRE,TELESAÚDE,POLO PREV.DE DOENCAS E AGRAVOS E PROMOCAO DA SAUDE,total_de_estabelecimentos
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1,-,-,-,1,1,-,4,-,-,...,-,4,1,-,-,-,-,-,-,35
110037,1,-,-,-,-,-,-,6,-,-,...,-,2,1,-,-,-,-,-,-,14
110040,-,-,-,-,-,-,-,4,-,-,...,-,4,1,-,-,-,-,-,-,19
110034,-,-,-,-,-,-,-,6,-,-,...,-,-,1,1,-,-,-,-,-,22
110002,-,1,1,2,1,1,-,13,-,-,...,-,11,4,-,6,-,-,-,-,124

# PROFISSIONAIS DE SAÚDE

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Separação da coluna "cidade" em "codigo" (código saúde) e "cidade" (nome do município).

4) Eliminação da coluna "cidade" para evitar duplicidade de informação (salva em outro dataframe).

5) Renomeação a coluna "Total" para não confundir com outras possíveis colunas semelhantes.

6) Definição do index como "codigo".

7) Reavaliação do dataframe após as mudanças realizadas.

In [30]:
profissionais_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/profissionais.csv")
profissionais_df.head()

,cidade,Assistente Social,Bioquímico/farmacêutico,Cirurgião Geral,Clínico Geral,Enfermeiro,Fisioterapeuta,Fonoaudiólogo,Gineco Obstetra,Médico de Família,Nutricionista,Odontólogo,Pediatra,Psicólogo,Psiquiatra,Radiologista,Sanitarista,Outras especialidades médicas,Outras ocupações de nível superior relac à Saúde,Total
0,110001 Alta Floresta D'Oeste,3,4,1,9,22,4,1,-,7,3,7,2,1,1,-,-,1,2,68
1,110037 Alto Alegre dos Parecis,1,-,-,2,12,2,1,-,4,1,1,-,1,-,-,-,-,2,27
2,110040 Alto Paraíso,-,2,-,3,11,3,-,-,2,1,1,-,2,-,-,-,-,1,26
3,110034 Alvorada D'Oeste,2,1,-,2,10,3,-,-,2,-,6,1,1,-,-,-,-,2,30
4,110002 Ariquemes,6,15,8,71,92,32,6,15,9,8,23,10,25,1,6,-,37,15,379

In [31]:
profissionais_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/profissionais.csv")
profissionais_df[["codigo", "cidade"]] = profissionais_df["cidade"].str.split(n=1, expand=True)
profissionais_df = profissionais_df.drop("cidade", axis=1)
profissionais_df = profissionais_df.rename(columns={"Total": "total_de_profissionais"})
profissionais_df = profissionais_df.set_index("codigo")
profissionais_df.head()

,Assistente Social,Bioquímico/farmacêutico,Cirurgião Geral,Clínico Geral,Enfermeiro,Fisioterapeuta,Fonoaudiólogo,Gineco Obstetra,Médico de Família,Nutricionista,Odontólogo,Pediatra,Psicólogo,Psiquiatra,Radiologista,Sanitarista,Outras especialidades médicas,Outras ocupações de nível superior relac à Saúde,total_de_profissionais
codigo,,,,,,,,,,,,,,,,,,,
110001,3,4,1,9,22,4,1,-,7,3,7,2,1,1,-,-,1,2,68
110037,1,-,-,2,12,2,1,-,4,1,1,-,1,-,-,-,-,2,27
110040,-,2,-,3,11,3,-,-,2,1,1,-,2,-,-,-,-,1,26
110034,2,1,-,2,10,3,-,-,2,-,6,1,1,-,-,-,-,2,30
110002,6,15,8,71,92,32,6,15,9,8,23,10,25,1,6,-,37,15,379

# MORTALIDADE GERAL

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Separação da coluna "cidade" em "codigo" (código saúde) e "cidade" (nome do município).

4) Escolha dos anos a serem preservados, "codigo" e "cidade" mantida
(aqui uma correção feita posteriormente à primeira tentativa de agregar todos os dataframes, pois inicialmente não tinha percebido que estou trabalhando com dois códigos diferentes de cidades)

5) Renomeação das colunas dos anos para não confundir com dados de outros dataframes.

6) Definição do index como "codigo".

7) Reavaliação do dataframe após as mudanças realizadas.

In [32]:
mortalidade_geral_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/mortalidadegeral.csv")
mortalidade_geral_df.head()

,cidade,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total
0,110001 Alta Floresta D'Oeste,93,81,90,167,97,111,107,116,84,...,84,122,112,108,145,109,137,128,140,2668
1,110037 Alto Alegre dos Parecis,-,14,12,28,28,27,27,42,42,...,45,54,43,45,53,45,54,48,52,867
2,110040 Alto Paraíso,25,26,26,23,36,43,32,49,44,...,62,58,57,83,78,70,71,75,75,1330
3,110034 Alvorada D'Oeste,71,63,71,54,68,76,65,56,66,...,52,73,81,55,84,96,81,76,77,1663
4,110002 Ariquemes,396,356,343,312,310,330,328,371,362,...,406,486,477,469,511,510,503,531,502,9789

In [33]:
mortalidade_geral_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/mortalidadegeral.csv")
mortalidade_geral_df[["codigo", "cidade"]] = mortalidade_geral_df["cidade"].str.split(n=1, expand=True)
mortalidade_geral_df = mortalidade_geral_df[["cidade", "2015", "2016", "2017", "2018", "2019", "codigo"]]
mortalidade_geral_df = mortalidade_geral_df.rename(columns={"2015": "mortalidade_geral_2015", "2016": "mortalidade_geral_2016", "2017": "mortalidade_geral_2017", "2018": "mortalidade_geral_2018", "2019": "mortalidade_geral_2019"})
mortalidade_geral_df = mortalidade_geral_df.set_index("codigo")
mortalidade_geral_df.head()

,cidade,mortalidade_geral_2015,mortalidade_geral_2016,mortalidade_geral_2017,mortalidade_geral_2018,mortalidade_geral_2019
codigo,,,,,,
110001,Alta Floresta D'Oeste,145,109,137,128,140
110037,Alto Alegre dos Parecis,53,45,54,48,52
110040,Alto Paraíso,78,70,71,75,75
110034,Alvorada D'Oeste,84,96,81,76,77
110002,Ariquemes,511,510,503,531,502

# MORTALIDADE INFANTIL

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Separação da coluna "cidade" em "codigo" (código saúde) e "cidade" (nome do município).

4) Escolha dos anos a serem preservados e o "codigo" mantido.

5) Renomeação das colunas dos anos para não confundir com dados de outros dataframes.

6) Definição do index como "codigo".

7) Reavaliação do dataframe após as mudanças realizadas.

In [34]:
mortalidade_infantil_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/mortalidadeinfantil.csv")
mortalidade_infantil_df.head()

,cidade,1996,1997,1998,1999,2000,2001,2002,2003,2004,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total
0,110001 Alta Floresta D'Oeste,12,14,17,36,10,12,12,7,5,...,6,5,7,2,7,5,5,3,3,214
1,110037 Alto Alegre dos Parecis,-,2,5,2,4,6,1,1,5,...,6,2,2,5,1,-,2,-,1,63
2,110040 Alto Paraíso,4,2,6,2,1,3,4,1,4,...,1,2,1,6,5,6,5,7,1,84
3,110034 Alvorada D'Oeste,9,18,14,7,7,14,7,7,9,...,2,-,2,1,4,-,3,-,1,140
4,110002 Ariquemes,69,54,47,35,30,30,32,34,21,...,16,15,19,23,18,26,23,26,18,680

In [35]:
mortalidade_infantil_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/mortalidadeinfantil.csv")
mortalidade_infantil_df[["codigo", "cidade"]] = mortalidade_infantil_df["cidade"].str.split(n=1, expand=True)
mortalidade_infantil_df = mortalidade_infantil_df[["2015", "2016", "2017", "2018", "2019", "codigo"]]
mortalidade_infantil_df = mortalidade_infantil_df.rename(columns={"2015": "mortalidade_infantil_2015", "2016": "mortalidade_infantil_2016", "2017": "mortalidade_infantil_2017", "2018": "mortalidade_infantil_2018", "2019": "mortalidade_infantil_2019"})
mortalidade_infantil_df = mortalidade_infantil_df.set_index("codigo")
mortalidade_infantil_df.head()

,mortalidade_infantil_2015,mortalidade_infantil_2016,mortalidade_infantil_2017,mortalidade_infantil_2018,mortalidade_infantil_2019
codigo,,,,,
110001,7,5,5,3,3
110037,1,-,2,-,1
110040,5,6,5,7,1
110034,4,-,3,-,1
110002,18,26,23,26,18

# NASCIMENTOS

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Separação da coluna "cidade" em "codigo" (código saúde) e "cidade" (nome do município).

4) Escolha dos anos a serem preservados e o "codigo" mantido.

5) Renomeação das colunas dos anos para não confundir com dados de outros dataframes.

6) Definição do index como "codigo".

7) Reavaliação do dataframe após as mudanças realizadas.

In [36]:
nascimentos_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/nascimentos.csv")
nascimentos_df.head()

,cidade,1994,1995,1996,1997,1998,1999,2000,2001,2002,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,Total
0,110001 Alta Floresta D'Oeste,2,699,778,587,591,689,617,721,586,...,398,386,382,341,373,326,354,408,367,12371
1,110037 Alto Alegre dos Parecis,-,-,-,150,205,164,231,179,137,...,199,189,163,172,149,168,172,160,154,3989
2,110040 Alto Paraíso,-,111,204,272,231,198,274,258,276,...,268,194,211,254,247,220,242,219,226,5991
3,110034 Alvorada D'Oeste,2,436,462,516,510,439,472,483,448,...,200,189,220,184,200,166,178,162,205,7770
4,110002 Ariquemes,8,1827,2333,2192,1820,1559,2122,2070,1948,...,1579,1339,1654,1647,1783,1662,1724,1682,1729,44008

In [37]:
nascimentos_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/nascimentos.csv")
nascimentos_df[["codigo", "cidade"]] = nascimentos_df["cidade"].str.split(n=1, expand=True)
nascimentos_df = nascimentos_df[["2015", "2016", "2017", "2018", "2019", "codigo"]]
nascimentos_df = nascimentos_df.rename(columns={"2015": "nascimentos_2015", "2016": "nascimentos_2016", "2017": "nascimentos_2017", "2018": "nascimentos_2018", "2019": "nascimentos_2019"})
nascimentos_df = nascimentos_df.set_index("codigo")
nascimentos_df.head()

,nascimentos_2015,nascimentos_2016,nascimentos_2017,nascimentos_2018,nascimentos_2019
codigo,,,,,
110001,373,326,354,408,367
110037,149,168,172,160,154
110040,247,220,242,219,226
110034,200,166,178,162,205
110002,1783,1662,1724,1682,1729

# COORDENADAS E DADOS DOS MUNICÍPIOS

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Eliminação de dados redundantes.

4) Renomeação de nomes de colunas.

5) Definição do index como "codigo_ibge".

6) Reavaliação do dataframe após as mudanças realizadas.

In [38]:
coordenadas_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/coordenadas.csv")
coordenadas_df.head()

,Cod UF,UF,Sgl UF,Cod IBGE,Nome Município,cod_latitude,cod_longitude,Sgl Região,Região
0,11,Rondônia,RO,1100015,Alta Floresta D'Oeste,-11.92870,-61.9958,N,Norte
1,11,Rondônia,RO,1100023,Ariquemes,-9.90612,-63.0330,N,Norte
2,11,Rondônia,RO,1100031,Cabixi,-13.49510,-60.5446,N,Norte
3,11,Rondônia,RO,1100049,Cacoal,-11.43470,-61.4566,N,Norte
4,11,Rondônia,RO,1100056,Cerejeiras,-13.18740,-60.8173,N,Norte

In [39]:
coordenadas_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/coordenadas.csv")
coordenadas_df = coordenadas_df.drop(["Cod UF", "UF", "Região"], axis=1)
coordenadas_df = coordenadas_df.rename(columns={"Sgl UF": "estado", "Cod IBGE": "codigo_ibge", "Nome Município": "cidade", "cod_latitude": "latitude", "cod_longitude": "longitude", "Sgl Região": "regiao"})
coordenadas_df = coordenadas_df.set_index("codigo_ibge")
coordenadas_df.head()

            estado                 cidade  latitude  longitude regiao
codigo_ibge
1100015         RO  Alta Floresta D'Oeste -11.92870   -61.9958      N
1100023         RO              Ariquemes  -9.90612   -63.0330      N
1100031         RO                 Cabixi -13.49510   -60.5446      N
1100049         RO                 Cacoal -11.43470   -61.4566      N
1100056         RO             Cerejeiras -13.18740   -60.8173      N

# POPULAÇÃO

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Renomeação de nomes de colunas.

4) Eliminação de dado redundante.

5) Definição do index como "codigo_ibge".

6) Reavaliação do dataframe após as mudanças realizadas.

In [40]:
populacao_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/populacao.csv")
populacao_df.head()

    código                   município  população
0  1100015  Alta Floresta D'Oeste (RO)      22945
1  1100023              Ariquemes (RO)     107863
2  1100031                 Cabixi (RO)       5312
3  1100049                 Cacoal (RO)      85359
4  1100056             Cerejeiras (RO)      16323

In [41]:
populacao_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/populacao.csv")
populacao_df = populacao_df.rename(columns={"código": "codigo_ibge", "população": "populacao"})
populacao_df = populacao_df.drop("município", axis=1)
populacao_df = populacao_df.set_index("codigo_ibge")
populacao_df.head()

             populacao
codigo_ibge
1100015          22945
1100023         107863
1100031           5312
1100049          85359
1100056          16323

# PIB

1) Avaliação do dataframe.

2) Importação do dataframe novamente para evitar qualquer erro no processo.

3) Escolha dos dados somente do ano de 2019.

4) Eliminação de dados redundantes.

5) Renomeação para "codigo_ibge"

6) Definição do index como "codigo_ibge".

7) Reavaliação do dataframe após as mudanças realizadas.

In [42]:
pib_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/pib.csv")
pib_df.head()

,Ano,Código da Grande Região,Nome da Grande Região,Código da Unidade da Federação,Sigla da Unidade da Federação,Nome da Unidade da Federação,Código do Município,Nome do Município,Região Metropolitana,Código da Mesorregião,...,"Valor adicionado bruto da Indústria, a preços correntes (R$ 1.000)","Valor adicionado bruto dos Serviços, a preços correntes - exceto Administração, defesa, educação e saúde públicas e seguridade social (R$ 1.000)","Valor adicionado bruto da Administração, defesa, educação e saúde públicas e seguridade social, a preços correntes (R$ 1.000)","Valor adicionado bruto total, a preços correntes (R$ 1.000)","Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto
0,2010,1,Norte,11,RO,Rondônia,1100015,Alta Floresta D'Oeste,NaN,1102,...,"16,119","62,496","93,245","241,120","20,957","262,077","10,731.18","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços
1,2010,1,Norte,11,RO,Rondônia,1100023,Ariquemes,NaN,1102,...,"287,139","494,946","343,868","1,199,664","165,030","1,364,694","15,103.86","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...
2,2010,1,Norte,11,RO,Rondônia,1100031,Cabixi,NaN,1102,...,"3,253","12,677","25,170","65,401","4,210","69,611","11,033.62","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços
3,2010,1,Norte,11,RO,Rondônia,1100049,Cacoal,NaN,1102,...,"182,052","465,447","298,454","1,041,212","145,282","1,186,494","15,095.15","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...
4,2010,1,Norte,11,RO,Rondônia,1100056,Cerejeiras,NaN,1102,...,"19,734","80,725","63,018","192,454","29,567","222,021","13,037.06","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...

In [43]:
pib_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/pib.csv")
pib_df.tail()

,Ano,Código da Grande Região,Nome da Grande Região,Código da Unidade da Federação,Sigla da Unidade da Federação,Nome da Unidade da Federação,Código do Município,Nome do Município,Região Metropolitana,Código da Mesorregião,...,"Valor adicionado bruto da Indústria, a preços correntes (R$ 1.000)","Valor adicionado bruto dos Serviços, a preços correntes - exceto Administração, defesa, educação e saúde públicas e seguridade social (R$ 1.000)","Valor adicionado bruto da Administração, defesa, educação e saúde públicas e seguridade social, a preços correntes (R$ 1.000)","Valor adicionado bruto total, a preços correntes (R$ 1.000)","Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto
55680,2019,5,Centro-oeste,52,GO,Goiás,5222005,Vianópolis,NaN,5205,...,"26,348","175,036","70,312","445,922","37,742","483,663","34,888.79",Demais serviços,"Agricultura, inclusive apoio à agricultura e a...","Administração, defesa, educação e saúde públic..."
55681,2019,5,Centro-oeste,52,GO,Goiás,5222054,Vicentinópolis,NaN,5205,...,"47,141","117,134","44,168","308,794","33,562","342,356","39,157.68","Agricultura, inclusive apoio à agricultura e a...",Demais serviços,"Administração, defesa, educação e saúde públic..."
55682,2019,5,Centro-oeste,52,GO,Goiás,5222203,Vila Boa,Região Integrada de Desenvolvimento do Distrit...,5204,...,"16,187","33,146","31,820","105,263","8,406","113,668","18,419.78","Administração, defesa, educação e saúde públic...",Demais serviços,"Agricultura, inclusive apoio à agricultura e a..."
55683,2019,5,Centro-oeste,52,GO,Goiás,5222302,Vila Propício,Região Integrada de Desenvolvimento do Distrit...,5204,...,"29,867","35,313","29,316","199,038","7,933","206,971","35,555.96","Agricultura, inclusive apoio à agricultura e a...",Demais serviços,"Administração, defesa, educação e saúde públic..."
55684,2019,5,Centro-oeste,53,DF,Distrito Federal,5300108,Brasília,Região Integrada de Desenvolvimento do Distrit...,5301,...,"9,453,608","125,261,853","107,219,249","242,927,104","30,686,608","273,613,711","90,742.75",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...

In [44]:
pib_df = pd.read_csv("/content/drive/MyDrive/tcc/dataframes/pib.csv")
pib_df = pib_df[pib_df["Ano"]==2019]
pib_df = pib_df.drop(["Ano","Código da Grande Região", "Nome da Grande Região", "Código da Unidade da Federação", "Sigla da Unidade da Federação", "Nome da Unidade da Federação", "Nome do Município"], axis=1)
pib_df = pib_df.rename(columns={"Código do Município": "codigo_ibge"})
pib_df = pib_df.set_index("codigo_ibge")
pib_df.head()

,Região Metropolitana,Código da Mesorregião,Nome da Mesorregião,Código da Microrregião,Nome da Microrregião,Código da Região Geográfica Imediata,Nome da Região Geográfica Imediata,Município da Região Geográfica Imediata,Código da Região Geográfica Intermediária,Nome da Região Geográfica Intermediária,...,"Valor adicionado bruto da Indústria, a preços correntes (R$ 1.000)","Valor adicionado bruto dos Serviços, a preços correntes - exceto Administração, defesa, educação e saúde públicas e seguridade social (R$ 1.000)","Valor adicionado bruto da Administração, defesa, educação e saúde públicas e seguridade social, a preços correntes (R$ 1.000)","Valor adicionado bruto total, a preços correntes (R$ 1.000)","Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto
codigo_ibge,,,,,,,,,,,,,,,,,,,,,
1100015,NaN,1102,Leste Rondoniense,11006,Cacoal,110005,Cacoal,do Entorno,1102,Ji-Paraná,...,"14,441","130,220","158,948","466,278","29,351","495,629","21,600.73","Administração, defesa, educação e saúde públic...",Demais serviços,"Pecuária, inclusive apoio à pecuária"
1100023,NaN,1102,Leste Rondoniense,11003,Ariquemes,110002,Ariquemes,Polo,1101,Porto Velho,...,"283,899","1,136,039","703,663","2,294,432","284,398","2,578,830","23,908.38",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...
1100031,NaN,1102,Leste Rondoniense,11008,Colorado do Oeste,110006,Vilhena,do Entorno,1102,Ji-Paraná,...,"3,267","25,547","43,646","133,961","5,998","139,959","26,347.78","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária","Agricultura, inclusive apoio à agricultura e a..."
1100049,NaN,1102,Leste Rondoniense,11006,Cacoal,110005,Cacoal,Polo,1102,Ji-Paraná,...,"178,514","1,070,827","564,238","2,006,655","253,988","2,260,644","26,483.95",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...
1100056,NaN,1102,Leste Rondoniense,11008,Colorado do Oeste,110006,Vilhena,do Entorno,1102,Ji-Paraná,...,"16,167","230,623","112,401","430,183","76,671","506,854","31,051.55",Comércio e reparação de veículos automotores e...,Demais serviços,"Administração, defesa, educação e saúde públic..."

# PRIMEIRA TENTATIVA DE AGREGAR (FALHOU)

Motivo de não funcionar foi que os 3 últimos dataframes estão com o Código do IBGE para as cidades mas os 16 primeiros com o Código da Saúde.
Feito df.info() de todos os dataframes e identificado que os 3 últimos são do mesmo tamanho e a "cidade" poderia ser mantida em qualquer um deles (optei por manter em coordenadas). Nos 16 primeiros nem toda doença foi notificada em toda 
cidade e portanto esses dataframes não poderiam ser usados para este propósito (manter o nome da cidade). Os dataframes de mortalidade e nascimentos podem ser usados com este fim (optei por manter em mortalidade geral).

In [45]:
# agg_df = pd.concat([aids_df, animais_df, dengue_df, hanseniase_df, hepatites_df, sifilis_adquirida_df, sifilis_congenita_df, sifilis_gestante_df, toxico_df, tuberculose_df, violencia_df, coordenadas_df, estabelecimentos_df, mortalidade_geral_df, mortalidade_infantil_df, nascimentos_df, pib_df, populacao_df, profissionais_df], axis=1)

In [46]:
# agg_df

# SEGUNDA TENTATIVA DE AGREGAR (FALHOU)

Após o erro descrito anteriormente, defini que o Código do SUS seria "codigo" e o index dos 16 primeiros dataframes, enquanto que o Código do IBGE seria "codigo_ibge" e o index dos 3 últimos dataframes. A intenção é logo na sequência conseguir agregar todos os dados usando "cidade" como index dos dois conjuntos de dados. Não entendi perfeitamente o motivo da falha, possivelmente alguns dados estão como cidades que não existem, exterior ou cidades não especificadas de cada estado.

In [47]:
# df1 = pd.concat([aids_df, animais_df, dengue_df, hanseniase_df, hepatites_df, sifilis_adquirida_df, sifilis_congenita_df, sifilis_gestante_df, toxico_df, tuberculose_df, violencia_df, estabelecimentos_df, mortalidade_geral_df, mortalidade_infantil_df, nascimentos_df, profissionais_df], axis=1)

In [48]:
# df1.info()

In [49]:
# df1.head()

In [50]:
# df2 = pd.concat([pib_df, coordenadas_df, populacao_df], axis=1)

In [51]:
# df2.info()

In [52]:
# df2.head()

In [53]:
# df1 = pd.concat([aids_df, animais_df, dengue_df, hanseniase_df, hepatites_df, sifilis_adquirida_df, sifilis_congenita_df, sifilis_gestante_df, toxico_df, tuberculose_df, violencia_df, estabelecimentos_df, mortalidade_geral_df, mortalidade_infantil_df, nascimentos_df, profissionais_df], axis=1)
# df2 = pd.concat([pib_df, coordenadas_df, populacao_df], axis=1)
# df1 = df1.reset_index()
# df2 = df2.reset_index()
# df1 = df1.set_index("cidade")
# df2 = df2.set_index("cidade")

In [54]:
# df1.info()

In [55]:
# df2.info()

In [56]:
# df3 = pd.concat([df1, df2])

In [57]:
# df3.info()

In [58]:
# df4 = pd.merge(df1,df2, how='outer', on="cidade")

In [59]:
# df4.info()

In [60]:
# df4.head()

# TERCEIRA TENTATIVA DE AGREGAR (FALHOU)

Após as falhas anteriores decidi criar um dataframe base somente com nome de cidades e codigo (saúde) e codigo_ibge. E só depois fazer left join com os demais dataframes. Falhou porque algumas cidades de diferentes estados possuem o mesmo nome.

In [61]:
# coordenadas_df.head()

In [62]:
# mortalidade_geral_df.head()

In [63]:
# coordenadas_df.info()

In [64]:
# mortalidade_geral_df.info()

In [65]:
# df1 = coordenadas_df.drop(["estado", "latitude", "longitude", "regiao"], axis=1)
# df1 = df1.reset_index()
# df1 = df1.set_index("cidade")
# df1.head()

In [66]:
# df2 = mortalidade_geral_df.drop(["mortalidade_geral_2015",	"mortalidade_geral_2016", "mortalidade_geral_2017", "mortalidade_geral_2018", "mortalidade_geral_2019"], axis=1)
# df2 = df2.reset_index()
# df2 = df2.set_index("cidade")
# df2.head()

In [67]:
# df3 = pd.merge(df1,df2,how='left',on="cidade")

In [68]:
# df3

In [69]:
# df3.info()

# QUARTA TENTATIVA DE AGREGAR (FUNCIONOU)

Finalmente, após as falhas anteriores, optei por criar o df1 com o codigo_ibge e o df2 com o codigo (SUS). Segue-se a separação dos códigos para identificar o estado de cada cidade. Retirada de municípios ignorados. Após definir as cidades com estados como índices, foi possível reunir em um só dataframe os dois códigos.

In [70]:
df1 = coordenadas_df.drop(["latitude", "longitude", "regiao"], axis=1)
df1 = df1.reset_index()
df1 = df1.set_index("cidade")
df1["codigo_ibge"] = df1["codigo_ibge"].astype(str)
df1.head()

                      codigo_ibge estado
cidade
Alta Floresta D'Oeste     1100015     RO
Ariquemes                 1100023     RO
Cabixi                    1100031     RO
Cacoal                    1100049     RO
Cerejeiras                1100056     RO

In [71]:
df2 = mortalidade_geral_df.drop(["mortalidade_geral_2015",	"mortalidade_geral_2016", "mortalidade_geral_2017", "mortalidade_geral_2018", "mortalidade_geral_2019"], axis=1)
df2 = df2.reset_index()
df2 = df2.set_index("cidade")
df2.head()

                         codigo
cidade
Alta Floresta D'Oeste    110001
Alto Alegre dos Parecis  110037
Alto Paraíso             110040
Alvorada D'Oeste         110034
Ariquemes                110002

In [72]:
df2

                         codigo
cidade
Alta Floresta D'Oeste    110001
Alto Alegre dos Parecis  110037
Alto Paraíso             110040
Alvorada D'Oeste         110034
Ariquemes                110002
...                         ...
Vicentinópolis           522205
Vila Boa                 522220
Vila Propício            522230
Município ignorado - GO  520000
Brasília                 530010

[5596 rows x 1 columns]

In [73]:
df2["numero_estado"] = df2["codigo"].str[0:2]
df2["numero_cidade"] = df2["codigo"].str[2:]
df2 = df2.reset_index()
df2.head()

                    cidade  codigo numero_estado numero_cidade
0    Alta Floresta D'Oeste  110001            11          0001
1  Alto Alegre dos Parecis  110037            11          0037
2             Alto Paraíso  110040            11          0040
3         Alvorada D'Oeste  110034            11          0034
4                Ariquemes  110002            11          0002

In [74]:
numeros_de_estado = df2["numero_estado"].unique()
numeros_de_estado

array(['11', '12', '13', '14', '15', '16', '17', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '31', '32', '33', '35', '41', '42',
       '43', '50', '51', '52', '53'], dtype=object)

In [75]:
df2

                       cidade  codigo numero_estado numero_cidade
0       Alta Floresta D'Oeste  110001            11          0001
1     Alto Alegre dos Parecis  110037            11          0037
2                Alto Paraíso  110040            11          0040
3            Alvorada D'Oeste  110034            11          0034
4                   Ariquemes  110002            11          0002
...                       ...     ...           ...           ...
5591           Vicentinópolis  522205            52          2205
5592                 Vila Boa  522220            52          2220
5593            Vila Propício  522230            52          2230
5594  Município ignorado - GO  520000            52          0000
5595                 Brasília  530010            53          0010

[5596 rows x 4 columns]

In [76]:
df3 = df2[df2["numero_cidade"]=="0000"]
df3.head()

                      cidade  codigo numero_estado numero_cidade
52   Município ignorado - RO  110000            11          0000
75   Município ignorado - AC  120000            12          0000
138  Município ignorado - AM  130000            13          0000
154  Município ignorado - RR  140000            14          0000
299  Município ignorado - PA  150000            15          0000

In [77]:
df3["estado"] = df3["cidade"].str[-2:]
df3 = df3[["estado", "numero_estado"]]
df3.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

    estado numero_estado
52      RO            11
75      AC            12
138     AM            13
154     RR            14
299     PA            15

In [78]:
df4 = pd.merge(df2,df3,how='outer')
df4

                       cidade  codigo numero_estado numero_cidade estado
0       Alta Floresta D'Oeste  110001            11          0001     RO
1     Alto Alegre dos Parecis  110037            11          0037     RO
2                Alto Paraíso  110040            11          0040     RO
3            Alvorada D'Oeste  110034            11          0034     RO
4                   Ariquemes  110002            11          0002     RO
...                       ...     ...           ...           ...    ...
5591           Vicentinópolis  522205            52          2205     GO
5592                 Vila Boa  522220            52          2220     GO
5593            Vila Propício  522230            52          2230     GO
5594  Município ignorado - GO  520000            52          0000     GO
5595                 Brasília  530010            53          0010    NaN

[5596 rows x 5 columns]

In [79]:
df4.loc[5595, "estado"] = "DF"
df4.loc[5595]

cidade           Brasília
codigo             530010
numero_estado          53
numero_cidade        0010
estado                 DF
Name: 5595, dtype: object

In [80]:
df_codigo_ibge_cidade_estado = df1
df_codigo_ibge_cidade_estado = df_codigo_ibge_cidade_estado.reset_index()
df_codigo_ibge_cidade_estado.head()

                  cidade codigo_ibge estado
0  Alta Floresta D'Oeste     1100015     RO
1              Ariquemes     1100023     RO
2                 Cabixi     1100031     RO
3                 Cacoal     1100049     RO
4             Cerejeiras     1100056     RO

In [81]:
df_codigo_cidade_estado = df4[["codigo", "cidade", "estado"]]
df_codigo_cidade_estado.head()

   codigo                   cidade estado
0  110001    Alta Floresta D'Oeste     RO
1  110037  Alto Alegre dos Parecis     RO
2  110040             Alto Paraíso     RO
3  110034         Alvorada D'Oeste     RO
4  110002                Ariquemes     RO

In [82]:
df_codigo_ibge_cidade_estado = df_codigo_ibge_cidade_estado.set_index(["cidade", "estado"])
df_codigo_cidade_estado = df_codigo_cidade_estado.set_index(["cidade", "estado"])

In [83]:
df_codigo_ibge_cidade_estado.head()

                             codigo_ibge
cidade                estado
Alta Floresta D'Oeste RO         1100015
Ariquemes             RO         1100023
Cabixi                RO         1100031
Cacoal                RO         1100049
Cerejeiras            RO         1100056

In [84]:
df_codigo_cidade_estado.head()

                                codigo
cidade                  estado
Alta Floresta D'Oeste   RO      110001
Alto Alegre dos Parecis RO      110037
Alto Paraíso            RO      110040
Alvorada D'Oeste        RO      110034
Ariquemes               RO      110002

In [85]:
codigos_df = pd.concat([df_codigo_cidade_estado, df_codigo_ibge_cidade_estado], axis=1)
codigos_df

                            codigo codigo_ibge
cidade              estado
Abadia de Goiás     GO      520005     5200050
Abadia dos Dourados MG      310010     3100104
Abadiânia           GO      520010     5200100
Abaetetuba          PA      150010     1500107
Abaeté              MG      310020     3100203
...                            ...         ...
Áurea               RS      430155     4301552
Ângulo              PR      410115     4101150
Érico Cardoso       BA      290050     2900504
Óbidos              PA      150510     1505106
Óleo                SP      353380     3533809

[5596 rows x 2 columns]

In [86]:
codigos_df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 5596 entries, ('Abadia de Goiás', 'GO') to ('Óleo', 'SP')
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   codigo       5596 non-null   object
 1   codigo_ibge  5570 non-null   object
dtypes: object(2)
memory usage: 275.8+ KB

In [87]:
codigos_df = codigos_df.dropna()
codigos_df = codigos_df.reset_index()
codigos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cidade       5570 non-null   object
 1   estado       5570 non-null   object
 2   codigo       5570 non-null   object
 3   codigo_ibge  5570 non-null   object
dtypes: object(4)
memory usage: 174.2+ KB

# AGREGAÇÃO COM CÓDIGO IBGE

Criação do arquivo df_ibge com os dados de pib, populacao e coordenadas.

In [88]:
codigos_df.head()

                cidade estado  codigo codigo_ibge
0      Abadia de Goiás     GO  520005     5200050
1  Abadia dos Dourados     MG  310010     3100104
2            Abadiânia     GO  520010     5200100
3           Abaetetuba     PA  150010     1500107
4               Abaeté     MG  310020     3100203

In [89]:
pib_df = pib_df.reset_index()
pib_df["codigo_ibge"] = pib_df["codigo_ibge"].astype(str)
pib_df.head()

,codigo_ibge,Região Metropolitana,Código da Mesorregião,Nome da Mesorregião,Código da Microrregião,Nome da Microrregião,Código da Região Geográfica Imediata,Nome da Região Geográfica Imediata,Município da Região Geográfica Imediata,Código da Região Geográfica Intermediária,...,"Valor adicionado bruto da Indústria, a preços correntes (R$ 1.000)","Valor adicionado bruto dos Serviços, a preços correntes - exceto Administração, defesa, educação e saúde públicas e seguridade social (R$ 1.000)","Valor adicionado bruto da Administração, defesa, educação e saúde públicas e seguridade social, a preços correntes (R$ 1.000)","Valor adicionado bruto total, a preços correntes (R$ 1.000)","Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto
0,1100015,NaN,1102,Leste Rondoniense,11006,Cacoal,110005,Cacoal,do Entorno,1102,...,"14,441","130,220","158,948","466,278","29,351","495,629","21,600.73","Administração, defesa, educação e saúde públic...",Demais serviços,"Pecuária, inclusive apoio à pecuária"
1,1100023,NaN,1102,Leste Rondoniense,11003,Ariquemes,110002,Ariquemes,Polo,1101,...,"283,899","1,136,039","703,663","2,294,432","284,398","2,578,830","23,908.38",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...
2,1100031,NaN,1102,Leste Rondoniense,11008,Colorado do Oeste,110006,Vilhena,do Entorno,1102,...,"3,267","25,547","43,646","133,961","5,998","139,959","26,347.78","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária","Agricultura, inclusive apoio à agricultura e a..."
3,1100049,NaN,1102,Leste Rondoniense,11006,Cacoal,110005,Cacoal,Polo,1102,...,"178,514","1,070,827","564,238","2,006,655","253,988","2,260,644","26,483.95",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...
4,1100056,NaN,1102,Leste Rondoniense,11008,Colorado do Oeste,110006,Vilhena,do Entorno,1102,...,"16,167","230,623","112,401","430,183","76,671","506,854","31,051.55",Comércio e reparação de veículos automotores e...,Demais serviços,"Administração, defesa, educação e saúde públic..."

In [90]:
populacao_df = populacao_df.reset_index()
populacao_df["codigo_ibge"] = populacao_df["codigo_ibge"].astype(str)
populacao_df.head()

  codigo_ibge  populacao
0     1100015      22945
1     1100023     107863
2     1100031       5312
3     1100049      85359
4     1100056      16323

In [91]:
coordenadas_df = coordenadas_df.reset_index()
coordenadas_df["codigo_ibge"] = coordenadas_df["codigo_ibge"].astype(str)
coordenadas_df.head()

  codigo_ibge estado                 cidade  latitude  longitude regiao
0     1100015     RO  Alta Floresta D'Oeste -11.92870   -61.9958      N
1     1100023     RO              Ariquemes  -9.90612   -63.0330      N
2     1100031     RO                 Cabixi -13.49510   -60.5446      N
3     1100049     RO                 Cacoal -11.43470   -61.4566      N
4     1100056     RO             Cerejeiras -13.18740   -60.8173      N

In [92]:
coordenadas_df = coordenadas_df.drop(["cidade", "estado"], axis=1)
coordenadas_df.head()

  codigo_ibge  latitude  longitude regiao
0     1100015 -11.92870   -61.9958      N
1     1100023  -9.90612   -63.0330      N
2     1100031 -13.49510   -60.5446      N
3     1100049 -11.43470   -61.4566      N
4     1100056 -13.18740   -60.8173      N

In [93]:
codigos_df = codigos_df.set_index("codigo_ibge")
pib_df = pib_df.set_index("codigo_ibge")
populacao_df = populacao_df.set_index("codigo_ibge")
coordenadas_df = coordenadas_df.set_index("codigo_ibge")

In [94]:
df_ibge = pd.concat([codigos_df, pib_df, populacao_df, coordenadas_df], axis=1)

# AGREGAÇÃO COM CÓDIGO SUS

Criação do arquivo df_sus com os dados de todos os outros dataframes.

In [95]:
aids_df.head()

        aids
codigo
110001     1
110037     1
110040     5
110034     5
110002   121

In [96]:
animais_df.head()

        animais
codigo
110001      192
110037      199
110040       62
110034       78
110002      252

In [97]:
dengue_df.head()

        dengue
codigo
110001     833
110037      90
110040      65
110034     126
110002     198

In [98]:
hanseniase_df.head()

        hanseniase
codigo
110001          51
110037          86
110040          43
110034          24
110002         224

In [99]:
hepatites_df.head()

        hepatites
codigo
110001         41
110037         12
110040         66
110034          8
110002        240

In [100]:
sifilis_adquirida_df.head()

        sadquirida
codigo
110001          28
110037          13
110040          18
110034          16
110002         296

In [101]:
sifilis_congenita_df.head()

        scongenita
codigo
110001           2
110037           1
110040           2
110034           1
110002           8

In [102]:
sifilis_gestante_df.head()

        sgestante
codigo
110001         12
110037          2
110040         11
110034          7
110002         89

In [103]:
toxico_df.head()

        toxico
codigo
110001     186
110037      31
110040      18
110034      35
110002     321

In [104]:
tuberculose_df.head()

        tuberculose
codigo
110001           26
110037            4
110040           12
110034            9
110002          177

In [105]:
violencia_df.head()

,autoprovocada_sim,autoprovocada_não,autoprovocada_ignorado,autoprovocada_branco,violencia
codigo,,,,,
110001,24,79,9,5,117
110037,1,3,-,-,4
110040,-,9,1,-,10
110034,26,24,1,-,51
110002,146,250,36,12,444

In [106]:
estabelecimentos_df.head()

,ACADEMIA DA SAÚDE,CENTRAL DE REGUALAÇÃO,CENTRAL DE REGULAÇÃO MÉDICA DAS URGÊNCIAS,CENTRO DE APOIO A SAÚDE DA FAMÍLIA-CASF,CENTRO DE ATENÇÃO HEMOTERÁPICA E/OU HEMATOLÓGICA,CENTRO DE ATENÇÃO PSICOSSOCIAL-CAPS,CENTRO DE PARTO NORMAL,CENTRO DE SAUDE/UNIDADE BASICA DE SAUDE,CENTRAL DE REGULACAO DE SERVICOS DE SAUDE,CENTRAL DE NOTIF. CAPTAÇÃO E DISTR. ÓRGÃOS ESTADUA,...,UNIDADE DE ATENCAO EM REGIME RESIDENCIAL,UNIDADE DE SERVICO DE APOIO DE DIAGNOSE E TERAPIA,UNIDADE DE VIGILANCIA EM SAUDE,UNIDADE MISTA,UNIDADE MOVEL DE NIVEL PRE-HOSP-URGENCIA/EMERGENCI,UNIDADE MOVEL FLUVIAL,UNIDADE MOVEL TERRESTRE,TELESAÚDE,POLO PREV.DE DOENCAS E AGRAVOS E PROMOCAO DA SAUDE,total_de_estabelecimentos
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1,-,-,-,1,1,-,4,-,-,...,-,4,1,-,-,-,-,-,-,35
110037,1,-,-,-,-,-,-,6,-,-,...,-,2,1,-,-,-,-,-,-,14
110040,-,-,-,-,-,-,-,4,-,-,...,-,4,1,-,-,-,-,-,-,19
110034,-,-,-,-,-,-,-,6,-,-,...,-,-,1,1,-,-,-,-,-,22
110002,-,1,1,2,1,1,-,13,-,-,...,-,11,4,-,6,-,-,-,-,124

In [107]:
mortalidade_geral_df = mortalidade_geral_df.drop("cidade", axis=1)
mortalidade_geral_df.head()

,mortalidade_geral_2015,mortalidade_geral_2016,mortalidade_geral_2017,mortalidade_geral_2018,mortalidade_geral_2019
codigo,,,,,
110001,145,109,137,128,140
110037,53,45,54,48,52
110040,78,70,71,75,75
110034,84,96,81,76,77
110002,511,510,503,531,502

In [108]:
mortalidade_infantil_df.head()

,mortalidade_infantil_2015,mortalidade_infantil_2016,mortalidade_infantil_2017,mortalidade_infantil_2018,mortalidade_infantil_2019
codigo,,,,,
110001,7,5,5,3,3
110037,1,-,2,-,1
110040,5,6,5,7,1
110034,4,-,3,-,1
110002,18,26,23,26,18

In [109]:
nascimentos_df.head()

,nascimentos_2015,nascimentos_2016,nascimentos_2017,nascimentos_2018,nascimentos_2019
codigo,,,,,
110001,373,326,354,408,367
110037,149,168,172,160,154
110040,247,220,242,219,226
110034,200,166,178,162,205
110002,1783,1662,1724,1682,1729

In [110]:
profissionais_df.head()

,Assistente Social,Bioquímico/farmacêutico,Cirurgião Geral,Clínico Geral,Enfermeiro,Fisioterapeuta,Fonoaudiólogo,Gineco Obstetra,Médico de Família,Nutricionista,Odontólogo,Pediatra,Psicólogo,Psiquiatra,Radiologista,Sanitarista,Outras especialidades médicas,Outras ocupações de nível superior relac à Saúde,total_de_profissionais
codigo,,,,,,,,,,,,,,,,,,,
110001,3,4,1,9,22,4,1,-,7,3,7,2,1,1,-,-,1,2,68
110037,1,-,-,2,12,2,1,-,4,1,1,-,1,-,-,-,-,2,27
110040,-,2,-,3,11,3,-,-,2,1,1,-,2,-,-,-,-,1,26
110034,2,1,-,2,10,3,-,-,2,-,6,1,1,-,-,-,-,2,30
110002,6,15,8,71,92,32,6,15,9,8,23,10,25,1,6,-,37,15,379

In [111]:
df_sus = pd.concat([aids_df, animais_df, dengue_df, hanseniase_df, hepatites_df, sifilis_adquirida_df, sifilis_congenita_df, sifilis_gestante_df, toxico_df, tuberculose_df, violencia_df, estabelecimentos_df, mortalidade_geral_df, mortalidade_infantil_df, nascimentos_df, profissionais_df], axis=1)

In [112]:
df_sus

,aids,animais,dengue,hanseniase,hepatites,sadquirida,scongenita,sgestante,toxico,tuberculose,...,Nutricionista,Odontólogo,Pediatra,Psicólogo,Psiquiatra,Radiologista,Sanitarista,Outras especialidades médicas,Outras ocupações de nível superior relac à Saúde,total_de_profissionais
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1.0,192.0,833.0,51.0,41.0,28.0,2.0,12.0,186.0,26.0,...,3,7,2,1,1,-,-,1,2,68.0
110037,1.0,199.0,90.0,86.0,12.0,13.0,1.0,2.0,31.0,4.0,...,1,1,-,1,-,-,-,-,2,27.0
110040,5.0,62.0,65.0,43.0,66.0,18.0,2.0,11.0,18.0,12.0,...,1,1,-,2,-,-,-,-,1,26.0
110034,5.0,78.0,126.0,24.0,8.0,16.0,1.0,7.0,35.0,9.0,...,-,6,1,1,-,-,-,-,2,30.0
110002,121.0,252.0,198.0,224.0,240.0,296.0,8.0,89.0,321.0,177.0,...,8,23,10,25,1,6,-,37,15,379.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
df_sus = df_sus.replace({"-":0})
df_sus = df_sus.fillna(0)
df_sus

,aids,animais,dengue,hanseniase,hepatites,sadquirida,scongenita,sgestante,toxico,tuberculose,...,Nutricionista,Odontólogo,Pediatra,Psicólogo,Psiquiatra,Radiologista,Sanitarista,Outras especialidades médicas,Outras ocupações de nível superior relac à Saúde,total_de_profissionais
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1.0,192.0,833.0,51.0,41.0,28.0,2.0,12.0,186.0,26.0,...,3,7,2,1,1,0,0,1,2,68.0
110037,1.0,199.0,90.0,86.0,12.0,13.0,1.0,2.0,31.0,4.0,...,1,1,0,1,0,0,0,0,2,27.0
110040,5.0,62.0,65.0,43.0,66.0,18.0,2.0,11.0,18.0,12.0,...,1,1,0,2,0,0,0,0,1,26.0
110034,5.0,78.0,126.0,24.0,8.0,16.0,1.0,7.0,35.0,9.0,...,0,6,1,1,0,0,0,0,2,30.0
110002,121.0,252.0,198.0,224.0,240.0,296.0,8.0,89.0,321.0,177.0,...,8,23,10,25,1,6,0,37,15,379.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
430000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
120000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
280000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0.0
500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0.0

# AGREGAÇÃO DADOS SUS E IBGE

Criação do arquivo df_base, quando todos os 19 Dataframes foram reunidos.

In [114]:
df_ibge = df_ibge.reset_index()
df_sus = df_sus.reset_index()
df_ibge = df_ibge.set_index("codigo")
df_sus = df_sus.set_index("codigo")

In [115]:
df = pd.concat([df_sus, df_ibge], axis=1)
df

,aids,animais,dengue,hanseniase,hepatites,sadquirida,scongenita,sgestante,toxico,tuberculose,...,"Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto,populacao,latitude,longitude,regiao
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1.0,192.0,833.0,51.0,41.0,28.0,2.0,12.0,186.0,26.0,...,"29,351","495,629","21,600.73","Administração, defesa, educação e saúde públic...",Demais serviços,"Pecuária, inclusive apoio à pecuária",22945.0,-11.92870,-61.9958,N
110037,1.0,199.0,90.0,86.0,12.0,13.0,1.0,2.0,31.0,4.0,...,"11,248","288,681","21,802.07","Administração, defesa, educação e saúde públic...","Agricultura, inclusive apoio à agricultura e a...","Pecuária, inclusive apoio à pecuária",13241.0,-12.14050,-61.8379,N
110040,5.0,62.0,65.0,43.0,66.0,18.0,2.0,11.0,18.0,12.0,...,"18,150","358,464","16,728.75","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,21428.0,-9.71470,-63.3193,N
110034,5.0,78.0,126.0,24.0,8.0,16.0,1.0,7.0,35.0,9.0,...,"10,423","260,348","18,065.91","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,14411.0,-11.34670,-62.2852,N
110002,121.0,252.0,198.0,224.0,240.0,296.0,8.0,89.0,321.0,177.0,...,"284,398","2,578,830","23,908.38",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...,107863.0,-9.90612,-63.0330,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
280000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
df = df.dropna(axis=0, subset=["codigo_ibge"])
df

,aids,animais,dengue,hanseniase,hepatites,sadquirida,scongenita,sgestante,toxico,tuberculose,...,"Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto,populacao,latitude,longitude,regiao
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1.0,192.0,833.0,51.0,41.0,28.0,2.0,12.0,186.0,26.0,...,"29,351","495,629","21,600.73","Administração, defesa, educação e saúde públic...",Demais serviços,"Pecuária, inclusive apoio à pecuária",22945.0,-11.92870,-61.9958,N
110037,1.0,199.0,90.0,86.0,12.0,13.0,1.0,2.0,31.0,4.0,...,"11,248","288,681","21,802.07","Administração, defesa, educação e saúde públic...","Agricultura, inclusive apoio à agricultura e a...","Pecuária, inclusive apoio à pecuária",13241.0,-12.14050,-61.8379,N
110040,5.0,62.0,65.0,43.0,66.0,18.0,2.0,11.0,18.0,12.0,...,"18,150","358,464","16,728.75","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,21428.0,-9.71470,-63.3193,N
110034,5.0,78.0,126.0,24.0,8.0,16.0,1.0,7.0,35.0,9.0,...,"10,423","260,348","18,065.91","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,14411.0,-11.34670,-62.2852,N
110002,121.0,252.0,198.0,224.0,240.0,296.0,8.0,89.0,321.0,177.0,...,"284,398","2,578,830","23,908.38",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...,107863.0,-9.90612,-63.0330,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522145,0.0,24.0,115.0,12.0,0.0,0.0,0.0,1.0,3.0,3.0,...,"2,444","51,875","14,821.32","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,3500.0,-13.50830,-48.7421,CO
522157,0.0,17.0,137.0,11.0,1.0,1.0,1.0,2.0,0.0,4.0,...,"1,956","47,960","16,804.54","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,2854.0,-14.28400,-49.9205,CO
220460,0.0,0.0,14.0,6.0,2.0,0.0,1.0,2.0,1.0,1.0,...,"1,292","30,136","7,773.10","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...,3877.0,-5.98900,-42.5601,NE
220590,0.0,0.0,21.0,5.0,0.0,7.0,3.0,3.0,3.0,8.0,...,"2,888","51,080","9,549.44","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...,5349.0,-8.00434,-43.8723,NE
250523,0.0,0.0,33.0,4.0,1.0,0.0,0.0,1.0,0.0,4.0,...,"1,817","60,564","9,533.11","Administração, defesa, educação e saúde públic...",Demais serviços,"Agricultura, inclusive apoio à agricultura e a...",6353.0,-6.91334,-35.2505,NE

In [117]:
df_base = df
df_base["aids"] = df_base["aids"].astype(int)
df_base["animais"] = df_base["animais"].astype(int)
df_base["dengue"] = df_base["dengue"].astype(int)
df_base["hanseniase"] = df_base["hanseniase"].astype(int)
df_base["hepatites"] = df_base["hepatites"].astype(int)
df_base["sadquirida"] = df_base["sadquirida"].astype(int)
df_base["scongenita"] = df_base["scongenita"].astype(int)
df_base["sgestante"] = df_base["sgestante"].astype(int)
df_base["toxico"] = df_base["toxico"].astype(int)
df_base["tuberculose"] = df_base["tuberculose"].astype(int)
df_base["violencia"] = df_base["violencia"].astype(int)
df_base["Código da Mesorregião"] = df_base["Código da Mesorregião"].astype(int)
df_base["Código da Microrregião"] = df_base["Código da Microrregião"].astype(int)
df_base["Código da Região Geográfica Imediata"] = df_base["Código da Região Geográfica Imediata"].astype(int)
df_base["Código da Região Geográfica Intermediária"] = df_base["Código da Região Geográfica Intermediária"].astype(int)
df_base["Código da Região Rural"] = df_base["Código da Região Rural"].astype(int)
df_base["populacao"] = df_base["populacao"].astype(int)
df_base["total_de_estabelecimentos"] = df_base["total_de_estabelecimentos"].astype(int)
df_base["total_de_profissionais"] = df_base["total_de_profissionais"].astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [118]:
df_base.head()

,aids,animais,dengue,hanseniase,hepatites,sadquirida,scongenita,sgestante,toxico,tuberculose,...,"Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto,populacao,latitude,longitude,regiao
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1,192,833,51,41,28,2,12,186,26,...,"29,351","495,629","21,600.73","Administração, defesa, educação e saúde públic...",Demais serviços,"Pecuária, inclusive apoio à pecuária",22945,-11.92870,-61.9958,N
110037,1,199,90,86,12,13,1,2,31,4,...,"11,248","288,681","21,802.07","Administração, defesa, educação e saúde públic...","Agricultura, inclusive apoio à agricultura e a...","Pecuária, inclusive apoio à pecuária",13241,-12.14050,-61.8379,N
110040,5,62,65,43,66,18,2,11,18,12,...,"18,150","358,464","16,728.75","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,21428,-9.71470,-63.3193,N
110034,5,78,126,24,8,16,1,7,35,9,...,"10,423","260,348","18,065.91","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,14411,-11.34670,-62.2852,N
110002,121,252,198,224,240,296,8,89,321,177,...,"284,398","2,578,830","23,908.38",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...,107863,-9.90612,-63.0330,N

In [119]:
df_base

,aids,animais,dengue,hanseniase,hepatites,sadquirida,scongenita,sgestante,toxico,tuberculose,...,"Impostos, líquidos de subsídios, sobre produtos, a preços correntes (R$ 1.000)","Produto Interno Bruto, a preços correntes (R$ 1.000)","Produto Interno Bruto per capita, a preços correntes (R$ 1,00)",Atividade com maior valor adicionado bruto,Atividade com segundo maior valor adicionado bruto,Atividade com terceiro maior valor adicionado bruto,populacao,latitude,longitude,regiao
codigo,,,,,,,,,,,,,,,,,,,,,
110001,1,192,833,51,41,28,2,12,186,26,...,"29,351","495,629","21,600.73","Administração, defesa, educação e saúde públic...",Demais serviços,"Pecuária, inclusive apoio à pecuária",22945,-11.92870,-61.9958,N
110037,1,199,90,86,12,13,1,2,31,4,...,"11,248","288,681","21,802.07","Administração, defesa, educação e saúde públic...","Agricultura, inclusive apoio à agricultura e a...","Pecuária, inclusive apoio à pecuária",13241,-12.14050,-61.8379,N
110040,5,62,65,43,66,18,2,11,18,12,...,"18,150","358,464","16,728.75","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,21428,-9.71470,-63.3193,N
110034,5,78,126,24,8,16,1,7,35,9,...,"10,423","260,348","18,065.91","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,14411,-11.34670,-62.2852,N
110002,121,252,198,224,240,296,8,89,321,177,...,"284,398","2,578,830","23,908.38",Demais serviços,"Administração, defesa, educação e saúde públic...",Comércio e reparação de veículos automotores e...,107863,-9.90612,-63.0330,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522145,0,24,115,12,0,0,0,1,3,3,...,"2,444","51,875","14,821.32","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,3500,-13.50830,-48.7421,CO
522157,0,17,137,11,1,1,1,2,0,4,...,"1,956","47,960","16,804.54","Administração, defesa, educação e saúde públic...","Pecuária, inclusive apoio à pecuária",Demais serviços,2854,-14.28400,-49.9205,CO
220460,0,0,14,6,2,0,1,2,1,1,...,"1,292","30,136","7,773.10","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...,3877,-5.98900,-42.5601,NE
220590,0,0,21,5,0,7,3,3,3,8,...,"2,888","51,080","9,549.44","Administração, defesa, educação e saúde públic...",Demais serviços,Comércio e reparação de veículos automotores e...,5349,-8.00434,-43.8723,NE
250523,0,0,33,4,1,0,0,1,0,4,...,"1,817","60,564","9,533.11","Administração, defesa, educação e saúde públic...",Demais serviços,"Agricultura, inclusive apoio à agricultura e a...",6353,-6.91334,-35.2505,NE

# PRIMEIRO INTERVALO ENTRE NOTEBOOKS
Originalmente o TCC foi feito em 4 diferentes notebooks devido à demora de processamento ao executar todas células quando necessário.

In [120]:
df_base = df.reset_index()
from google.colab import files
df_base.to_csv('df_base.csv', encoding = 'utf-8-sig', index=False) 
files.download('df_base.csv')